version: '2.0'

services:

  vms-client:
    container_name: vms-client
    expose:
      - 3000
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: vmsClient/DockerFile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - '.:/project/VMS-app'

  vmsprocessor:
    container_name: vmsprocessor
    build:
      context: .
      dockerfile: vmsProcessor/DockerFile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    depends_on:
      - validator
    volumes:
      - '.:/project/VMS-app'

  rest-api:
    image: hyperledger/sawtooth-rest-api:chime
    container_name: sawtooth-rest-api-default
    ports:
      - "8008:8008"
    depends_on:
      - validator
    entrypoint: sawtooth-rest-api -C tcp://validator:4004 --bind rest-api:8008

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:chime
    container_name: sawtooth-settings-tp-default
    depends_on:
      - validator
    entrypoint: settings-tp -vv -C tcp://validator:4004

  validator:
    image: hyperledger/sawtooth-validator:chime
    container_name: sawtooth-validator-default
    expose:
      - 4004
    ports:
      - "4004:4004"
    # start the validator with an empty genesis batch
    entrypoint: "bash -c \"sawadm keygen && sawtooth keygen my_key && sawset genesis -k /root/.sawtooth/keys/my_key.priv && sawset proposal create -k /root/.sawtooth/keys/my_key.priv sawtooth.consensus.algorithm.name=Devmode sawtooth.consensus.algorithm.version=0.1 -o config.batch && sawadm genesis config-genesis.batch config.batch && sawtooth-validator -vv --endpoint tcp://validator:8800 --bind component:tcp://eth0:4004 --bind network:tcp://eth0:8800 --bind consensus:tcp://eth0:5050 \""

  devmode-engine:
    image: hyperledger/sawtooth-devmode-engine-rust:chime
    container_name: sawtooth-devmode-engine-rust-default
    depends_on:
      - validator
    entrypoint: devmode-engine-rust -C tcp://validator:5050
