
FROM ubuntu:xenial

COPY --from=sawtooth-cli-builder /project/python3-sawtooth-cli*.deb /tmp

COPY --from=sawtooth-validator-builder /project/python3-sawtooth-validator*.deb /tmp

RUN echo "deb http://repo.sawtooth.me/ubuntu/bumper/nightly xenial universe" >> /etc/apt/sources.list \
    && (apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 44FC67F19B2466EA \
    || apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 44FC67F19B2466EA) \
    && apt-get update \
    && dpkg -i /tmp/python3-sawtooth-*.deb || true \
    && apt-get -f -y install

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - \
    && apt-get install -y nodejs

WORKDIR /project/VMS-app/vmsProcessor

CMD npm install && npm start

EXPOSE 4004/tcp

RUN \
    if [ ! -z $HTTP_PROXY ] && [ -z $http_proxy ]; then \
    http_proxy=$HTTP_PROXY; \
    fi; \
    if [ ! -z $HTTPS_PROXY ] && [ -z $https_proxy ]; then \
    https_proxy=$HTTPS_PROXY; \
    fi; \
    if [ ! -z $http_proxy ]; then \
    npm config set proxy $http_proxy; \
    fi; \
    if [ ! -z $https_proxy ]; then \
    npm config set https-proxy $https_proxy; \
    fi
