
FROM ubuntu:xenial

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get clean && apt-get update

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - \
   && apt-get install -y nodejs

WORKDIR /project/VMS-app/vmsClient

CMD npm install && npm start

EXPOSE 3000

RUN \
   if [ ! -z $HTTP_PROXY ] && [ -z $http_proxy ]; then \
   http_proxy=$HTTP_PROXY; \
   fi; \
   if [ ! -z $HTTPS_PROXY ] && [ -z $https_proxy ]; then \
   https_proxy=$HTTPS_PROXY; \
   fi; \
   if [ ! -z $http_proxy ]; then \
   npm config set proxy $http_proxy; \
   fi; \
   if [ ! -z $https_proxy ]; then \
   npm config set https-proxy $https_proxy; \
   fi
